//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18047
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighwayServer.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HighwayServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;sec_selt&quot;&gt;
        ///		&lt;option value=&quot;10010&quot;&gt;國道1號&lt;/option&gt;
        ///	&lt;option value=&quot;10019&quot;&gt;國1高架&lt;/option&gt;
        ///	&lt;option value=&quot;10031&quot;&gt;國道3甲&lt;/option&gt;
        ///	&lt;option value=&quot;10038&quot;&gt;港西聯外道路&lt;/option&gt;
        ///	&lt;option value=&quot;10039&quot;&gt;南港聯絡道&lt;/option&gt;
        ///	&lt;option value=&quot;10020&quot;&gt;國道2號&lt;/option&gt;
        ///	&lt;option value=&quot;10030&quot;&gt;國道3號&lt;/option&gt;
        ///	&lt;option value=&quot;10040&quot;&gt;國道4號&lt;/option&gt;
        ///	&lt;option value=&quot;10050&quot;&gt;國道5號&lt;/option&gt;
        ///	&lt;option value=&quot;10060&quot;&gt;國道6號&lt;/option&gt;
        ///	&lt;option value=&quot;10080&quot;&gt;國道8號&lt;/option&gt;
        ///	&lt;option value=&quot;10100&quot;&gt;國道10號&lt;/option&gt;
        ///	&lt;option value=&quot;20620&quot;&gt;快速公路62號&lt;/option&gt;
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetfrees_3Fid_3Dsec_selt_26df_3D1 {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetfrees_3Fid_3Dsec_selt_26df_3D1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;372800&quot;&gt;高雄端&lt;/option&gt;
        ///	&lt;option value=&quot;371800&quot;&gt;五甲&lt;/option&gt;
        ///	&lt;option value=&quot;370400&quot;&gt;五甲系統&lt;/option&gt;
        ///	&lt;option value=&quot;369600&quot;&gt;瑞隆路&lt;/option&gt;
        ///	&lt;option value=&quot;367400&quot;&gt;高雄&lt;/option&gt;
        ///	&lt;option value=&quot;362400&quot;&gt;鼎金系統&lt;/option&gt;
        ///	&lt;option value=&quot;356200&quot;&gt;楠梓&lt;/option&gt;
        ///	&lt;option value=&quot;349400&quot;&gt;岡山&lt;/option&gt;
        ///	&lt;option value=&quot;346800&quot;&gt;岡山收費站&lt;/option&gt;
        ///	&lt;option value=&quot;342300&quot;&gt;高科&lt;/option&gt;
        ///	&lt;option value=&quot;338300&quot;&gt;路竹&lt;/option&gt;
        ///	&lt;option value=&quot;335100&quot;&gt;仁德服務區&lt;/option&gt;
        ///	&lt;option value=&quot;330700&quot;&gt;仁德系統&lt;/option&gt;
        ///	&lt;opti [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10010_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10010_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;70500&quot;&gt;楊梅端&lt;/option&gt;
        ///	&lt;option value=&quot;60300&quot;&gt;中壢轉接二&lt;/option&gt;
        ///	&lt;option value=&quot;58650&quot;&gt;中壢轉接一&lt;/option&gt;
        ///	&lt;option value=&quot;52500&quot;&gt;機場系統&lt;/option&gt;
        ///	&lt;option value=&quot;36000&quot;&gt;泰山轉接道&lt;/option&gt;
        ///	&lt;option value=&quot;32100&quot;&gt;五股轉接道&lt;/option&gt;
        ///	&lt;option value=&quot;26100&quot;&gt;環北&lt;/option&gt;
        ///	&lt;option value=&quot;20700&quot;&gt;下塔悠&lt;/option&gt;
        ///	&lt;option value=&quot;18800&quot;&gt;堤頂&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10019_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10019_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;20400&quot;&gt;鶯歌系統&lt;/option&gt;
        ///	&lt;option value=&quot;18500&quot;&gt;大湳&lt;/option&gt;
        ///	&lt;option value=&quot;11600&quot;&gt;南桃園&lt;/option&gt;
        ///	&lt;option value=&quot;8600&quot;&gt;機場系統&lt;/option&gt;
        ///	&lt;option value=&quot;5000&quot;&gt;大竹&lt;/option&gt;
        ///	&lt;option value=&quot;900&quot;&gt;大園&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10020_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10020_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;431500&quot;&gt;大鵬灣端&lt;/option&gt;
        ///	&lt;option value=&quot;430500&quot;&gt;林邊&lt;/option&gt;
        ///	&lt;option value=&quot;424500&quot;&gt;南州&lt;/option&gt;
        ///	&lt;option value=&quot;421200&quot;&gt;崁頂&lt;/option&gt;
        ///	&lt;option value=&quot;415200&quot;&gt;竹田系統&lt;/option&gt;
        ///	&lt;option value=&quot;411300&quot;&gt;竹田收費站&lt;/option&gt;
        ///	&lt;option value=&quot;407300&quot;&gt;麟洛&lt;/option&gt;
        ///	&lt;option value=&quot;400200&quot;&gt;長治&lt;/option&gt;
        ///	&lt;option value=&quot;391600&quot;&gt;九如&lt;/option&gt;
        ///	&lt;option value=&quot;383000&quot;&gt;燕巢系統&lt;/option&gt;
        ///	&lt;option value=&quot;373000&quot;&gt;田寮收費站&lt;/option&gt;
        ///	&lt;option value=&quot;369500&quot;&gt;田寮&lt;/option&gt;
        ///	&lt;option value=&quot;363800&quot;&gt;關廟服務區&lt;/option&gt;
        ///	&lt;opt [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10030_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10030_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;5600&quot;&gt;深坑端&lt;/option&gt;
        ///	&lt;option value=&quot;5100&quot;&gt;木柵&lt;/option&gt;
        ///	&lt;option value=&quot;3600&quot;&gt;萬芳&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10031_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10031_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;3073&quot;&gt;中和路&lt;/option&gt;
        ///	&lt;option value=&quot;2424&quot;&gt;德安路&lt;/option&gt;
        ///	&lt;option value=&quot;0&quot;&gt;基隆港&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10038_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10038_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;1400&quot;&gt;南港&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10039_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10039_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;17160&quot;&gt;豐原端&lt;/option&gt;
        ///	&lt;option value=&quot;14300&quot;&gt;后豐&lt;/option&gt;
        ///	&lt;option value=&quot;11700&quot;&gt;台中系統&lt;/option&gt;
        ///	&lt;option value=&quot;9000&quot;&gt;神岡&lt;/option&gt;
        ///	&lt;option value=&quot;2300&quot;&gt;中港系統&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10040_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10040_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;54300&quot;&gt;蘇澳&lt;/option&gt;
        ///	&lt;option value=&quot;46700&quot;&gt;羅東&lt;/option&gt;
        ///	&lt;option value=&quot;38600&quot;&gt;宜蘭&lt;/option&gt;
        ///	&lt;option value=&quot;30300&quot;&gt;頭城&lt;/option&gt;
        ///	&lt;option value=&quot;29700&quot;&gt;頭城收費站&lt;/option&gt;
        ///	&lt;option value=&quot;14700&quot;&gt;坪林行控&lt;/option&gt;
        ///	&lt;option value=&quot;4000&quot;&gt;石碇&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10050_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10050_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;37300&quot;&gt;埔里端&lt;/option&gt;
        ///	&lt;option value=&quot;34000&quot;&gt;埔里&lt;/option&gt;
        ///	&lt;option value=&quot;29000&quot;&gt;愛蘭&lt;/option&gt;
        ///	&lt;option value=&quot;17000&quot;&gt;國姓&lt;/option&gt;
        ///	&lt;option value=&quot;5000&quot;&gt;東草屯&lt;/option&gt;
        ///	&lt;option value=&quot;3000&quot;&gt;舊正&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10060_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10060_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;15500&quot;&gt;新化端&lt;/option&gt;
        ///	&lt;option value=&quot;14600&quot;&gt;新化系統&lt;/option&gt;
        ///	&lt;option value=&quot;9700&quot;&gt;新市&lt;/option&gt;
        ///	&lt;option value=&quot;6500&quot;&gt;台南系統&lt;/option&gt;
        ///	&lt;option value=&quot;2400&quot;&gt;新吉&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10080_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10080_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;33800&quot;&gt;旗山端&lt;/option&gt;
        ///	&lt;option value=&quot;22600&quot;&gt;嶺口&lt;/option&gt;
        ///	&lt;option value=&quot;19700&quot;&gt;燕巢系統&lt;/option&gt;
        ///	&lt;option value=&quot;13000&quot;&gt;燕巢&lt;/option&gt;
        ///	&lt;option value=&quot;6700&quot;&gt;仁武&lt;/option&gt;
        ///	&lt;option value=&quot;1900&quot;&gt;鼎金系統&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10100_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F10100_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;18760&quot;&gt;瑞濱端&lt;/option&gt;
        ///	&lt;option value=&quot;16000&quot;&gt;瑞芳&lt;/option&gt;
        ///	&lt;option value=&quot;9400&quot;&gt;暖暖&lt;/option&gt;
        ///	&lt;option value=&quot;5500&quot;&gt;大華系統&lt;/option&gt;
        ///	&lt;option value=&quot;3700&quot;&gt;七堵&lt;/option&gt;
        ///	&lt;option value=&quot;2000&quot;&gt;瑪東系統&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20620_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20620_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;28668&quot;&gt;新店端&lt;/option&gt;
        ///	&lt;option value=&quot;26550&quot;&gt;中和二&lt;/option&gt;
        ///	&lt;option value=&quot;23750&quot;&gt;中和&lt;/option&gt;
        ///	&lt;option value=&quot;22450&quot;&gt;中和一&lt;/option&gt;
        ///	&lt;option value=&quot;20821&quot;&gt;板橋&lt;/option&gt;
        ///	&lt;option value=&quot;17820&quot;&gt;江子翠&lt;/option&gt;
        ///	&lt;option value=&quot;15020&quot;&gt;三重&lt;/option&gt;
        ///	&lt;option value=&quot;11820&quot;&gt;五股二&lt;/option&gt;
        ///	&lt;option value=&quot;10000&quot;&gt;五股一&lt;/option&gt;
        ///	&lt;option value=&quot;6480&quot;&gt;觀音山&lt;/option&gt;
        ///	&lt;option value=&quot;850&quot;&gt;八里&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20640_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20640_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;27200&quot;&gt;大溪端&lt;/option&gt;
        ///	&lt;option value=&quot;23200&quot;&gt;平鎮三&lt;/option&gt;
        ///	&lt;option value=&quot;20700&quot;&gt;平鎮二&lt;/option&gt;
        ///	&lt;option value=&quot;19000&quot;&gt;平鎮一&lt;/option&gt;
        ///	&lt;option value=&quot;18000&quot;&gt;平鎮系統&lt;/option&gt;
        ///	&lt;option value=&quot;10800&quot;&gt;新屋&lt;/option&gt;
        ///	&lt;option value=&quot;5580&quot;&gt;觀音一&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20660_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20660_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;23529&quot;&gt;竹東端&lt;/option&gt;
        ///	&lt;option value=&quot;20000&quot;&gt;竹東&lt;/option&gt;
        ///	&lt;option value=&quot;15800&quot;&gt;芎林&lt;/option&gt;
        ///	&lt;option value=&quot;10200&quot;&gt;新竹科園&lt;/option&gt;
        ///	&lt;option value=&quot;7500&quot;&gt;新竹二&lt;/option&gt;
        ///	&lt;option value=&quot;5000&quot;&gt;新竹一&lt;/option&gt;
        ///	&lt;option value=&quot;900&quot;&gt;南寮端&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20680_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20680_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;31042&quot;&gt;獅潭端&lt;/option&gt;
        ///	&lt;option value=&quot;29550&quot;&gt;開礦村三號&lt;/option&gt;
        ///	&lt;option value=&quot;28420&quot;&gt;開礦村二號&lt;/option&gt;
        ///	&lt;option value=&quot;26100&quot;&gt;開礦村一號&lt;/option&gt;
        ///	&lt;option value=&quot;24550&quot;&gt;石圍牆&lt;/option&gt;
        ///	&lt;option value=&quot;22610&quot;&gt;119甲&lt;/option&gt;
        ///	&lt;option value=&quot;20590&quot;&gt;銅鑼&lt;/option&gt;
        ///	&lt;option value=&quot;15760&quot;&gt;公館&lt;/option&gt;
        ///	&lt;option value=&quot;11806&quot;&gt;頭屋二&lt;/option&gt;
        ///	&lt;option value=&quot;10120&quot;&gt;頭屋一&lt;/option&gt;
        ///	&lt;option value=&quot;6550&quot;&gt;造橋&lt;/option&gt;
        ///	&lt;option value=&quot;5000&quot;&gt;新港&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20720_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20720_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;15000&quot;&gt;北屯端&lt;/option&gt;
        ///	&lt;option value=&quot;13000&quot;&gt;北屯&lt;/option&gt;
        ///	&lt;option value=&quot;10940&quot;&gt;西屯三&lt;/option&gt;
        ///	&lt;option value=&quot;10000&quot;&gt;西屯二&lt;/option&gt;
        ///	&lt;option value=&quot;8900&quot;&gt;西屯一&lt;/option&gt;
        ///	&lt;option value=&quot;7140&quot;&gt;南屯二&lt;/option&gt;
        ///	&lt;option value=&quot;5500&quot;&gt;南屯一&lt;/option&gt;
        ///	&lt;option value=&quot;4000&quot;&gt;高鐵台中&lt;/option&gt;
        ///	&lt;option value=&quot;1650&quot;&gt;成功&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20740_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20740_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;32600&quot;&gt;中興系統&lt;/option&gt;
        ///	&lt;option value=&quot;26800&quot;&gt;林厝&lt;/option&gt;
        ///	&lt;option value=&quot;22880&quot;&gt;員林&lt;/option&gt;
        ///	&lt;option value=&quot;19070&quot;&gt;埔心&lt;/option&gt;
        ///	&lt;option value=&quot;15250&quot;&gt;埔鹽系統&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20760_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20760_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;43520&quot;&gt;古坑系統&lt;/option&gt;
        ///	&lt;option value=&quot;39370&quot;&gt;古坑&lt;/option&gt;
        ///	&lt;option value=&quot;32575&quot;&gt;斗南&lt;/option&gt;
        ///	&lt;option value=&quot;30430&quot;&gt;雲林系統&lt;/option&gt;
        ///	&lt;option value=&quot;25420&quot;&gt;虎尾&lt;/option&gt;
        ///	&lt;option value=&quot;22500&quot;&gt;土庫&lt;/option&gt;
        ///	&lt;option value=&quot;15230&quot;&gt;元長&lt;/option&gt;
        ///	&lt;option value=&quot;8040&quot;&gt;東勢&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20780_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20780_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;34740&quot;&gt;水上系統&lt;/option&gt;
        ///	&lt;option value=&quot;32700&quot;&gt;嘉義&lt;/option&gt;
        ///	&lt;option value=&quot;30570&quot;&gt;中和&lt;/option&gt;
        ///	&lt;option value=&quot;25890&quot;&gt;水上&lt;/option&gt;
        ///	&lt;option value=&quot;22535&quot;&gt;嘉義系統&lt;/option&gt;
        ///	&lt;option value=&quot;18620&quot;&gt;鹿草&lt;/option&gt;
        ///	&lt;option value=&quot;14385&quot;&gt;祥和&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20820_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20820_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;41780&quot;&gt;玉井端&lt;/option&gt;
        ///	&lt;option value=&quot;35206&quot;&gt;二溪&lt;/option&gt;
        ///	&lt;option value=&quot;32487&quot;&gt;頭社&lt;/option&gt;
        ///	&lt;option value=&quot;27788&quot;&gt;官田系統&lt;/option&gt;
        ///	&lt;option value=&quot;26462&quot;&gt;渡頭&lt;/option&gt;
        ///	&lt;option value=&quot;21183&quot;&gt;西庄&lt;/option&gt;
        ///	&lt;option value=&quot;17600&quot;&gt;麻豆&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20840_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20840_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;20000&quot;&gt;關廟&lt;/option&gt;
        ///	&lt;option value=&quot;18900&quot;&gt;台19甲&lt;/option&gt;
        ///	&lt;option value=&quot;16900&quot;&gt;歸仁&lt;/option&gt;
        ///	&lt;option value=&quot;11800&quot;&gt;大潭&lt;/option&gt;
        ///	&lt;option value=&quot;10260&quot;&gt;上崙&lt;/option&gt;
        ///	&lt;option value=&quot;8740&quot;&gt;仁德系統&lt;/option&gt;
        ///	&lt;option value=&quot;5310&quot;&gt;台南&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20860_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20860_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;select id=&quot;end_selt&quot;&gt;
        ///		&lt;option value=&quot;22500&quot;&gt;竹田端&lt;/option&gt;
        ///	&lt;option value=&quot;21150&quot;&gt;竹田系統&lt;/option&gt;
        ///	&lt;option value=&quot;15800&quot;&gt;萬丹&lt;/option&gt;
        ///	&lt;option value=&quot;9680&quot;&gt;大發&lt;/option&gt;
        ///	&lt;option value=&quot;7025&quot;&gt;大寮&lt;/option&gt;
        ///	&lt;option value=&quot;2200&quot;&gt;鳳山&lt;/option&gt;
        ///&lt;/select&gt; 的當地語系化字串。
        /// </summary>
        internal static string http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20880_3Flc_3D1_26id_3Dend_selt {
            get {
                return ResourceManager.GetString("http_3A_2F_2F1968_freeway_gov_tw_2Fcommon_2Fgetnodsecs_2Ffid_2F20880_3Flc_3D1_26i" +
                        "d_3Dend_selt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 test 的當地語系化字串。
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 test 的當地語系化字串。
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
    }
}
